app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.custLogin, name='index'),
    path('logout', views.user_logout, name='logout'),
    path('facebook_login', views.facebookLogin, name='facebook_login'),
    path('twitter_login', views.twitterLogin, name='twitter_login'),
    path('cust_login/', views.custLogin, name='cust_login'),
    path('cust_register/', views.custRegister, name='cust_register'),
    path('merchant_login/', views.merchantLogin, name='merchant_login'),
    path('merchant_register/', views.merchantRegister, name='merchant_register'),
    path('myaccount/',views.profile,name='myaccount'),
    path('merchant_transaction/' , views.transaction, name='merchant_transaction'),
    path('customer_transaction/',views.transaction,name='customer_transaction'),
    path('add_product/',views.addProduct, name='add_product'),
    path('product/',views.productList,name='product'),
    path('product_status/',views.set_status, name='product_status'),
    path('edit_product/',views.editProduct,name='edit_product'),
    path('search_by_price/',views.search_page,name='search_by_price'),
    path('search_location/',views.searchLocation,name='search_location'),
    path('product_details/',views.product_detail,name='product_details'),
    path('delivery/<trans_id>/',views.delivery,name= 'delivery'),
    path('payment/<trans_id>/',views.payment,name='payment'),
    path('search_product/',views.search_product,name ='search_product')
]

whisky_fancy/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from data_crawler import views

urlpatterns = [
    path('', views.index, name='index'),
    path('data_crawler/', include('data_crawler.urls')),

    path('admin/', admin.site.urls),

]

whisky_fantasy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

from app import views

urlpatterns = [
    path('', views.custLogin, name='login'),
    path('app/', include('app.urls')),
    path('accounts/',include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/forms/ProductForm.py
from django import forms

from app.tables.Whisky import Whisky


class ProductForm(forms.ModelForm):
    class Meta:
        model = Whisky
        fields = ('whisky_name', 'whisky_price', 'whisky_quantity', 'whisky_description', 'whisky_location', 'whisky_img',
                  'whisky_img_link', 'whisky_status','merchant')

app/controllers/Product.py
# Import External Libraries
import json
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone

# Import Internal Libraries
from app.forms.ProductForm import ProductForm
from app.tables import UserProfile, WhiskyList
from app.tables.Transaction import Transaction
from app.tables.Whisky import Whisky, Location
from django.views import View

'''
Overview:
    productList:    list out all the Whisky [Merchant]
    search_page:    Sort all Whisky according to the Price in ascending order [Customer]
    search_product: render product list for search page when searching for some products [Customer]
    product_detail: render product detail page for the specific Whisky [Customer]
    addProduct:     to add new whisky for sale [Merchant]
    editProduct:    to edit the existing whisky for sale [Merchant]
    set_status:     void the existing Whisky [Merchant], product become unavailable for sale
'''

@login_required
def productList(request):  # render product list for merchant
    profile = UserProfile.objects.get(user=request.user)
    product = Whisky.objects.filter(merchant=request.user).order_by('-id')
    print(product)

    return render(request, 'app/product.html', {'product': product, 'profile': profile})


def search_page(request):  # render product list for search page
    product = Whisky.objects.filter(whisky_status=1).order_by('whisky_price')
    print(product)
    return render(request, 'app/search_by_price.html', {'product': product})


def search_product(request):  # render product list for search page when searching for some products
    if request.method == 'POST':
        query = request.POST.get('query')
        product = Whisky.objects.filter(whisky_name__icontains=query, whisky_status=1)
        print(product)
        return render(request, 'app/search_by_price.html', {'product': product})


def product_detail(request):  # render product details when browsing a single product
    if request.method == 'GET':
        profile = UserProfile.objects.get(user=request.user)
        product_id = request.GET.get('product_id')
        product = Whisky.objects.get(id=product_id)
        return render(request, 'app/detail_page.html', {'product': product, 'profile': profile})
    else:
        product_id = request.POST.get('whisky_id')
        product = Whisky.objects.get(id=product_id)
        quantity = request.POST.get('trans_quantity')

        # create a transaction when post a request and reverse to next page
        transaction_info = Transaction.objects.create(
            customer=request.user,
            whisky=product,
            merchant=product.merchant.username,
            trans_price=product.whisky_price,
            trans_quantity=quantity,
            trans_amount=product.whisky_price * int(quantity),
            trans_status=0,
            trans_time=timezone.now(),
        )
        return redirect(reverse('app:delivery', kwargs={'trans_id': transaction_info.id}))


@login_required
def addProduct(request):
    profile = UserProfile.objects.get(user=request.user)
    locationObj = Location.objects.all()
    locations = json.dumps([location.location_name for location in locationObj])

    print(locations)
    if request.method == 'POST':
        product = ProductForm(request.POST, request.FILES)
        print(product)
        if product.is_valid():
            product.save()
            return redirect(reverse('app:product'))
        else:
            print('--------- Error -------------')
            print(product.errors)
    else:
        product = ProductForm()
    return render(request, 'app/add_product.html', {'product': product, 'locations': locations, 'profile': profile})


@login_required
def editProduct(request):
    profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        product_id = request.POST.get('id')
        print(product_id)
        if product_id is not None:
            product = Whisky.objects.get(id=product_id)
            product.whisky_name = request.POST.get('whisky_name')
            product.whisky_price = request.POST.get('whisky_price')
            product.whisky_quantity = request.POST.get('whisky_quantity')
            product.whisky_description = request.POST.get('whisky_description')
            picture = request.FILES.get('whisky_img')
            if picture is not None:
                product.whisky_img = request.FILES.get('whisky_img')
            product.whisky_location = Location.objects.get(location_name=request.POST.get('whisky_location'))
            product.save()
            return redirect(reverse('app:product'))

    else:
        product_id = request.GET.get('product_id')
        product = Whisky.objects.get(id=product_id)
        locationObj = Location.objects.all()
        locations = json.dumps([location.location_name for location in locationObj])
        return render(request, 'app/edit_product.html',
                      {'product': product, 'locations': locations, 'profile': profile})


@login_required
def set_status(request):
    product_id = request.GET['id']
    status = request.GET['status']

    try:
        product = Whisky.objects.get(id=product_id)
    except Whisky.DoseNotExist:
        return HttpResponse(-1)
    except ValueError:
        return HttpResponse(-1)
    product.whisky_status = status
    product.save()
    return render(request, 'app/product.html', {'id': product_id, 'status': status})

######################################################################################################
class ShowCategoryView(View):
    def create_context_dict(self, category_name_slug):
        context_dict = {}
        try:
            category = WhiskyList.objects.get(slug=category_name_slug)
            pages = Whisky.objects.filter(category=category).order_by('-views')

            context_dict['whisky'] = pages
            context_dict['whisky_list'] = category
        except WhiskyList.DoesNotExist:
            context_dict['whisky'] = None
            context_dict['whisky_list'] = None
        return context_dict

    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'app/category.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST['query'].strip()
        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
        return render(request, 'app/category.html', context_dict)

class SearchPrice(View):
    def create_context_dict(self, whisky_name_slug):
        context_dict = {}
        try:
            whisky = Whisky.objects.get(slug=category_name_slug).order_by('whisky_price')
            context_dict['whisky'] = category
        except Whisky.DoesNotExist:
            context_dict['whisky'] = None
        return context_dict

    def get(self, request, whisky_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'app/search_by_price.html', context_dict)

class CategorySuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''
        category_list = get_category_list(max_results=8, starts_with=suggestion)
        if len(category_list) == 0:
            category_list = WhiskyList.objects.order_by('-views')
        return render(request, 'app/search_by_price.html', {'categories': category_list})

def get_category_list(max_results=0, starts_with=''):
    category_list = []
    if starts_with:
        category_list = WhiskyList.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]
    return category_list

app/controllers/Profile.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from app.tables import UserProfile

# profile allows users to view and edit their personal details
@login_required
def profile(request):
    # Connect to UserProfile Model to obtain user details
    user_profile = UserProfile.objects.get(user=request.user)
    # When user intends to submit their changes within their user profile
    if request.method == 'POST':
        print(user_profile)
        # save the changes of their email address
        user_profile.user.email = request.POST.get('email')
        user_profile.user.save()
        # Only update their profile picture if any changes
        if 'picture' in request.FILES:
            user_profile.picture = request.FILES['picture']
            user_profile.save()

    return render(request, 'app/profile.html', {'profile': user_profile})

templates/app/base_mainPage.html
<!DOCTYPE html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Whishy Fantasy</title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/frontend_style.css"/>
    <link rel="icon" href="{% static 'images/icon.png' %}">

    {% block head %}
    {% endblock %}
</head>

<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flux">
  <div class="container">
      <div class="row col-md-12 col-sm-12">
          <!-- icon+homepage -->
          {% if profile.role == '1' %}
          <a class="navbar-brand" href="#">Whisky Fantasy</a>
          {% else %}
          <a class="navbar-brand" href="{% url 'app:search_by_price'%}">Whisky Fantasy</a>
          {% endif %}
          <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent">
              <span class="navbar-toggler-icon"></span>
          </button>

          <!-- right side menu -->
          <ul class="navbar-nav navbar-collapse" id="navbarSupportedContent">
              <li class="nav-item dropdown ml-auto">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false" style="text-align: right;">
                      Hi, {{user}}
                  </a>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'app:myaccount'%}">My Account</a>
                      {% if profile.role == '1' %}
                      <a class="dropdown-item" href="{% url 'app:merchant_transaction'%}">My Transaction</a>
                      {% else %}
                      <a class="dropdown-item" href="{% url 'app:search_by_price'%}">Search Product</a>
                      <a class="dropdown-item" href="{% url 'app:customer_transaction'%}">My Transaction</a>
                      {% endif %}
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'app:cust_login'%}">Log Out</a>
      </div>
      </li>
      </ul>
  </div>
  </div>
</nav>

{% block body_block %}
{% endblock %}

<!-- footer -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
{% block footer %}
{% endblock %}
</body>
</html>

templates/app/login_customer.html
{% extends 'app/base.html' %}
{% load static %}

{% block header %}
<link href="https://getbootstrap.com/docs/4.2/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

{% block body_block %}

<!-- head bar -->
<div class="container bg-light">
    <div class="row" style="background-color:black;height: 90px;border-radius: 5px;">
        <h2 class="col-md-12 text-center" style="padding-top: 25px; color:#D29062;">Whisky Fantasy</h2>
    </div>
    <!-- login form -->
    <div class="row" style="background-color:white;">
        <form class="form-signin" role="form" method="post" action="{% url 'app:cust_login' %}" >
            {% csrf_token %}
            <div class="btn-group btn-group-sm" style="width: inherit;">
                <button type="button" class="btn" style="background-color: #D29062;color:white;">Customer</button>
                <button type="button" class="btn" onclick="location.href = '{% url 'app:merchant_login' %}'"
                    style="border-color: #D29062; color: #d29062;">Merchant</button>
            </div><br /><br />

            {% if err_msg %}
                <p style="color:red;">{{ err_msg }}</p>
            {% endif %}

            <label for="id_username">Username :</label><br />
            <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required
                autofocus>
            <label for="id_password">Password :</label>
            <input type="password" name="password" id="id_password" class="form-control" placeholder="Password"
                required><br />
            <button class="btn btn-lg btn-block" type="submit" value="Sublmit"
                style="background-color: #818181; color: white;">Log In</button>
            <p class="text-center">or</p>
            <button class="btn btn-lg btn-primary btn-block" id="facebook-button" data-url="{% url 'app:facebook_login' %}" data-redirect="{% url 'app:myaccount' %}">Login with
                Facebook</button>
            <button class="btn btn-lg btn-primary btn-block" id="twitter-button" onclick="window.location.href = '{% url 'app:twitter_login' %}'">Login with
                Twitter</button>
        </form>
    </div>
    <!-- register link -->
    <div class="row" style="background-color:black;height: 40px;">
        <div class="col-md-12 text-center" style="color: #D29062;padding-top: 5px;">
            Not a Member?
            <a href="{% url 'app:cust_register' %}">Register Here</a>
        </div>
    </div>

</div>

{% endblock %}

templates/app/login_merchant.html
{% extends 'app/base.html' %}
{% load static %}

{% block header %}       
<link href="https://getbootstrap.com/docs/4.2/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

    {% block body_block %}
    <!-- head bar -->
    <div class="container" >
        <div class="row" style="background-color:black;height: 90px;border-radius: 5px;">
            <h2 class="col-md-12 text-center" style="padding-top: 25px;color:#D29062;">Whisky Fantasy</h2>
        </div>
        <!-- login form -->
        <div class="row" style="background-color:white;height: 450px;">
            <form class="form-signin" role="form" method="post" action="{% url 'app:merchant_login' %}" >
                {% csrf_token %}
                <div class="btn-group btn-group-sm" style="width: inherit;">
                    <button type="button" class="btn" onclick="location.href = '{% url 'app:cust_login' %}'"
                        style="border-color: #D29062;color: #d29062;">Customer</button>
                    <button type="button" class="btn" style="background-color: #D29062;color:white;">Merchant</button>
                </div><br /><br />
                {% if form.errors %}
                    <p style="color:red;">{{ form.errors }}</p>
                {% endif %}

                <label for="id_username">Username :</label><br />
                <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required
                    autofocus>
                <label for="id_password">Password :</label>
                <input type="password" name="password" id="id_password" class="form-control" placeholder="Password"
                    required><br/>
                <button class="btn btn-lg btn-block" type="submit" value="Sublmit" style="background-color: #818181;color: white;">Log In</button>
            </form>
            <p style="color:red;">{{ form.errors }}</p>
        </div>
        <!-- register link -->
        <div class="row" style="background-color:black;height: 40px;">
            <div class="col-md-12 text-center" style="color: #D29062;padding-top: 5px;">
                Not a Member?
                <a href="{% url 'app:merchant_register' %}">Register Here</a>
            </div>
        </div>

    </div>

    {% endblock %}

templates/app/product.html
{% extends 'app/base_mainPage.html' %}

  {% block head %}
  <link rel="stylesheet" href="/static/css/productList.css">
    <!-- add new class tag 'off' to be easily get the clicked button-->
<style>
  .off {}
  .edit{}
</style>
  {% endblock %}

  {% block body_block %}
  <!-- web tabs -->
  <div class="container mt-5">
    <div class="row no-gutters">
      <div class="btn-group col-md-3">
        <button class="btn btn-md active" aria-pressed="true">
          <strong>Products</strong>
        </button>
        <button class="btn btn-switch btn-md active" aria-pressed="true"
          onclick="location='/app/merchant_transaction/'">
          <strong>Transactions</strong>
        </button>
      </div>

      <div class="col-md-9 " style="text-align: right;">
        <button class="btn btn-iso btn-sm active" aria-pressed="true" onclick="location='{% url 'app:add_product'%}'">
          Add Product
        </button>
      </div>
      <!-- product list -->
      <ul class="list-group col-md-12">
        {% for Whisky in product %}

        <li class="list-group-item d-flex justify-content-between lh-condensed" id="{{Whisky.id}}">
          <div class="col-md-3">
            {% if Whisky.whisky_img %}
            <img src="/media/{{Whisky.whisky_img}}" alt="No pictures" style="width: 100px;height: 100px;">
            {% else %}
            <img src="/static/images/product.png" alt="No pictures" style="width: 70px;height: 100px;">
            
            {% endif %}
          </div>
          <div class="col-md-7" >
            <h6 class="my-0">{{Whisky.whisky_name}}</h6>
            <small class="text-muted">{{Whisky.whisky_description}}</small><br>
            <p class="my-0 pt-2">Quantity:{{Whisky.whisky_quantity}}</p>
            <strong>£{{Whisky.whisky_price}}</strong>
          </div>
          <div class="col-md-2 ">
              {% if Whisky.whisky_status == 2 %}
              <p id="flag{{Whisky.id}}">Removed</p>
              {% else %}
              <button class="btn btn-switch btn-md active mb-2" id="edit{{Whisky.id}}" style="width: 100px;"
                onclick="location='{% url 'app:edit_product'%}?product_id={{Whisky.id}}'">Edit</button><br>
              <button class="btn btn-switch btn-md active off" style="width: 100px;" data-id="{{Whisky.id}}" data-status="2">Remove</button>
              <p id="flag{{Whisky.id}}"></p>
              {% endif %}

          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block footer %}
<!-- JavaScript -->
<script src="/static/script/remove_product.js"></script>
{% endblock %}

templates/app/profile.html
{% extends 'app/base_mainPage.html' %}
{% load static %}
{% block body_block %}
    
    <div class="container mt-5">
        <div class="row ">
            <!-- user photo -->
            <div class="col-md-5 text-center">
                <h2 style="color: #D29062;">My Account</h2>
                {% if profile.picture %}
                <img src="/media/{{profile.picture}}" alt="You have not uploaded a photo!" class="p-4" onclick=""
                    style="width: 200px;height: 200px;">               
                {% else %}
                <img src="/static/images/profile.png" alt="No photo!" class="p-4" onclick=""
                    style="width: 200px;height: 200px;">
                {% endif %}
            </div>

            <!-- user profile -->
            <div class="col-md-7">
                <form class="form-horizontal" role="form" method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <br /><br /><br />
                    <div class="form-group row">
                        <label class="col-sm-2">Username:</label>
                        <label id="username" class="font-weight-bold ml-3">{{profile.user}}</label>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 pt-1" for="id_email" >E-mail :</label>
                        <input type="text" name="email" id="id_email" class="col-md-8 form-control ml-3" placeholder="email"
                            value="{{profile.user.email}}" required>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 pt-1"  >Password :</label>
                        <a class="font-weight-bold ml-3 pt-1 text-dark"  href="{% url 'auth_password_change'%}"><u>Change Password</u></a>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2">Picture :</label>
                        <input class="ml-3" type="file" name="picture" id="file" onchange="getPhoto(this)" /></div>

                    <div class="form-group row mt-5">
                        <button class="btn col-sm-2 " type="submit" value="Sublmit"
                            style="background-color: #D29062;color:white;margin-left: 300px;">Save</button>
                        {% if profile.role == '0' %}
                        <button class="btn col-sm-2" type="button" onclick="location='{% url 'app:search_by_price'%}'"
                            style="border-color: #D29062;color: #d29062;background-color:white;margin-left: 30px;">Cancel</button>
                        {% else %}
                        <button class="btn col-sm-2" type="button" onclick="location='{% url 'app:merchant_transaction'%}'"
                            style="border-color: #D29062;color: #d29062;background-color:white;margin-left: 30px;">Cancel</button>
                        {% endif %}

                    </div>

                </form>

            </div>

        </div>

    </div> 
{% endblock %}

templates/app/register_customer.html
{% extends 'app/base.html' %}
{% load static %}

{% block header %}       
<link href="https://getbootstrap.com/docs/4.2/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

    {% block body_block %}
    <!-- head bar --> 
    <div class="container" >
        <div class="row" style="background-color:black;height: 90px;border-radius: 5px;">
            <h2 class="col-md-12 text-center" style="padding-top: 25px;color:#D29062;">Whisky Fantasy</h2>
        </div>
        <!-- register form -->
        <div class="row" style="background-color:white;">
            <form class="form-signin" role="form" method="post" action="{% url 'app:cust_register' %}">
                {% csrf_token %}
                <div class="btn-group btn-group-sm" style="width: inherit;">
                    <button type="button" class="btn" style="background-color: #D29062;color:white;">Customer</button>
                    <button type="button" class="btn" onclick="location.href = '{% url 'app:merchant_register' %}'"
                        style="border-color: #D29062;color: #d29062;">Merchant</button>
                </div><br /><br />
                <input type="hidden" name="role" value=0>

                <label for="id_email">E-mail :</label>
                <input type="text" name="email" id="id_email" class="form-control" placeholder="email" required
                    autofocus>
                <label for="id_username">Username :</label>
                <input type="text" name="username" id="id_username" class="form-control" placeholder="Username"
                    required>
                <label for="id_password1">Password :</label>
                <input type="password" name="password" id="id_password1" class="form-control" placeholder="Password"
                    required>
                <label for="id_password2">Confirm Password :</label>
                <input type="password" name="cust_password_c" id="id_password2" class="form-control"
                    placeholder="Password" required><br />
                <button class="btn btn-lg btn-block" type="submit" value="Sublmit"
                    style="background-color: #818181;color: white;">Sign Up</button>

                {{ user_form.errors }}
                {% if registered %}
                <p>Registered successfully! Please login</p>
                {% endif %}

            </form>
        </div>
        <!-- login link -->
        <div class="row" style="background-color:black;height: 40px;">
            <div class="col-md-12 text-center" style="color: #D29062;padding-top: 5px;">
                Already a Member?
                <a href="{% url 'app:cust_login' %}">Log In</a>
            </div>
        </div>

    </div>
    <!-- JavaScript -->
    <script src="/static/script/register_validation.js/"></script>
    {% endblock %}

templates/app/register_merchant.html
{% extends 'app/base.html' %}
{% load static %}

{% block header %}       
<link href="https://getbootstrap.com/docs/4.2/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

    {% block body_block %}
    <!-- head bar -->
    <div class="container" >
        <div class="row" style="background-color:black;height: 90px;border-radius: 5px;">
            <h2 class="col-md-12 text-center" style="padding-top: 25px;color:#D29062;">Whisky Fantasy</h2>
        </div>
        <!-- register form -->
        <div class="row" style="background-color:white;">
            <form class="form-signin" role="form" method="post" action="{% url 'app:merchant_register' %}">
                {% csrf_token %}
                <div class="btn-group btn-group-sm" style="width: inherit;">
                    <button type="button" class="btn" onclick="location.href = '{% url 'app:cust_register' %}'"
                        style="border-color: #D29062;color: #d29062;">Customer</button>
                    <button type="button" class="btn" style="background-color: #D29062;color:white;">Merchant</button>
                </div><br /><br />
                <input type="hidden" name="role" value=1>

                <label for="id_email">E-mail :</label>
                <input type="text" name="email" id="id_email" class="form-control" placeholder="email" required
                    autofocus>
                <label for="id_username">Username :</label>
                <input type="text" name="username" id="id_username" class="form-control" placeholder="Username"
                    required>
                <label for="id_password1">Password :</label>
                <input type="password" name="password" id="id_password1" class="form-control" placeholder="Password"
                    required>
                <label for="id_password2">Confirm Password :</label>
                <input type="password" name="password" id="id_password2" class="form-control" placeholder="Password"
                    required><br />
                <button class="btn btn-lg btn-block" id="sign" type="submit" 
                    style="background-color: #818181;color: white;">Sign Up</button>
                {% if not user_form.is_valid %}
                <p style="color:red">{{ user_form.errors }}</p>
                {% endif %}
                {% if registered %}
                <p>Registered successfully! Please login</p>
                {% endif %}
            </form>
        </div>
        <!-- Login link -->
        <div class="row" style="background-color:black;height: 40px;">
            <div class="col-md-12 text-center" style="color: #D29062;padding-top: 5px;">
                Already a Member?
                <a href="{% url 'app:merchant_login' %}">Log In</a>
            </div>
        </div>
    </div>
    <!-- JavaScript -->
    <script src="/static/script/register_validation.js/"></script>

    {% endblock %}